export const FETCH_PLACES_LOADING = 'FETCH_PLACES_LOADING';
export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_PLACESS_SUCCESS = 'FETCH_PLACESS_SUCCESS';

export const DELETE_PLACE = 'DELETE_PLACE';
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS';

export const ADD_PLACE_LOADING = 'ADD_PLACE_LOADING';
export const ADD_PLACE_SUCCESS = 'ADD_PLACE_SUCCESS';

export const SET_LOADING = 'SET_LOADING';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const HANDLE_AUTH = 'HANDLE_AUTH';
export const CHECK_AUTH = 'CHECK_AUTH';
export const LOGOUT = 'LOGOUT';
